# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ""
author: "Stefan/Yuzhao Heng 衡雨昭"
email: stefan.hg@outlook.com
github_username: StefanHeng
description:
  My personal website. Contains my resume, education, working experiences, hobbies, etc..

baseurl: ""
domain: StefanHeng.github.io
url: https://StefanHeng.github.io

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

head_scripts:
  - "/assets/js/index.js"
  - "/assets/js/sh-carousel.js"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

name: "Stefan Heng"
last_modified: "Dec. 6th"
masthead_title: ""

social:
  links:
    - "https://www.facebook.com/stefan.heng.792/"
    - "https://www.instagram.com/stefan.heng/"
    - "https://www.linkedin.com/in/stefan-heng-41690716b/"

author:
  name: "Stefan/Yuzhao Heng <br> 衡雨昭"
  avatar: "/assets/images/Stefan with Art.jpg"
  bio: "A developer & researcher. Hopefully a designer. <a href=\"/StefanHeng\"><i class=\"fas fa-feather-alt\"></i></a>"
  location: "Ann Arbor, MI"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/StefanHeng"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stefan-heng-41690716b/"
    # - label: "Resume"
      # icon: "fab fa-fw fa-black-tie"
      # url: "https://drive.google.com/file/d/1E9WPX8KMI6EQltD2sCN9kxW5_rKSlIzX/view?usp=sharing"
    - label: "Curriculum Vitae"
      icon: "fas fa-fw fa-user-tie"
      url: "https://drive.google.com/file/d/1kW4L_ydS8Y4iisMHScDi8Cl3nr8gHri1/view?usp=drivesdk"
    - label: "Portfolio"
      icon: "fas fa-fw fa-paint-brush"
      url: "https://drive.google.com/file/d/1FcTTuime6AhLqfNWy-pgd88gPkR62Kel/view?usp=sharing"



atom_feed:
  hide: true
